alter table absences add constraint absences_pkey PRIMARY KEY (id);
alter table app_settings add constraint app_settings_pkey PRIMARY KEY (key);
alter table attendance_marks add constraint attendance_marks_pkey PRIMARY KEY (session_id, student_id);
alter table audit_log add constraint audit_log_pkey PRIMARY KEY (id);
alter table backups add constraint backups_pkey PRIMARY KEY (id);
alter table chart_of_accounts add constraint chart_of_accounts_pkey PRIMARY KEY (id);
alter table class_sessions add constraint class_sessions_pkey PRIMARY KEY (id);
alter table discount_types add constraint discount_types_pkey PRIMARY KEY (id);
alter table employee_payslips add constraint employee_payslips_pkey PRIMARY KEY (id);
alter table employees add constraint employees_pkey PRIMARY KEY (id);
alter table enrolments add constraint enrolments_pkey PRIMARY KEY (id);
alter table event_budget_items add constraint event_budget_items_pkey PRIMARY KEY (id);
alter table events add constraint events_pkey PRIMARY KEY (id);
alter table fee_schedule add constraint fee_schedule_pkey PRIMARY KEY (id);
alter table guardians add constraint guardians_pkey PRIMARY KEY (id);
alter table inventory_movements add constraint inventory_movements_pkey PRIMARY KEY (id);
alter table invoice_lines add constraint invoice_lines_pkey PRIMARY KEY (id);
alter table invoices add constraint invoices_pkey PRIMARY KEY (id);
alter table kpay_transactions add constraint kpay_transactions_pkey PRIMARY KEY (id);
alter table ledger_entries add constraint ledger_entries_pkey PRIMARY KEY (id);
alter table levels add constraint levels_pkey PRIMARY KEY (id);
alter table payments add constraint payments_pkey PRIMARY KEY (id);
alter table po_items add constraint po_items_pkey PRIMARY KEY (id);
alter table products add constraint products_pkey PRIMARY KEY (id);
alter table purchase_orders add constraint purchase_orders_pkey PRIMARY KEY (id);
alter table rooms add constraint rooms_pkey PRIMARY KEY (id);
alter table schedule_assignments add constraint schedule_assignments_pkey PRIMARY KEY (id);
alter table section_teachers add constraint section_teachers_pkey PRIMARY KEY (section_id, teacher_id);
alter table sections add constraint sections_pkey PRIMARY KEY (id);
alter table student_discounts add constraint student_discounts_pkey PRIMARY KEY (id);
alter table students add constraint students_pkey PRIMARY KEY (id);
alter table suppliers add constraint suppliers_pkey PRIMARY KEY (id);
alter table teacher_payslips add constraint teacher_payslips_pkey PRIMARY KEY (id);
alter table class_sessions add constraint class_sessions_section_id_session_date_key UNIQUE (section_id, session_date);
alter table discount_types add constraint discount_types_code_key UNIQUE (code);
alter table employee_payslips add constraint employee_payslips_employee_id_pay_month_key UNIQUE (employee_id, pay_month);
alter table enrolments add constraint enrolments_student_id_section_id_start_date_key UNIQUE (student_id, section_id, start_date);
alter table guardians add constraint guardians_notes_uniq UNIQUE (notes);
alter table levels add constraint levels_code_key UNIQUE (code);
alter table rooms add constraint rooms_name_key UNIQUE (name);
alter table sections add constraint sections_level_id_time_slot_is_online_key UNIQUE (level_id, time_slot, is_online);
alter table students add constraint students_external_id_uniq UNIQUE (external_id);
alter table teacher_payslips add constraint teacher_payslips_teacher_id_pay_month_key UNIQUE (teacher_id, pay_month);
alter table absences add constraint absences_role_check CHECK ((role = ANY (ARRAY['MT'::text, 'CT'::text, 'OTHER'::text])));
alter table absences add constraint absences_hours_check CHECK ((hours > (0)::numeric));
alter table attendance_marks add constraint attendance_marks_status_check CHECK ((status = ANY (ARRAY['Present'::text, 'Absent'::text, 'Leave'::text, 'Break'::text])));
alter table audit_log add constraint audit_log_action_check CHECK ((action = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])));
alter table backups add constraint backups_source_check CHECK ((source = ANY (ARRAY['auto'::text, 'manual'::text])));
alter table chart_of_accounts add constraint chart_of_accounts_category_check CHECK ((category = ANY (ARRAY['Income'::text, 'Expense'::text, 'Equity'::text, 'Asset'::text, 'Liability'::text])));
alter table discount_types add constraint discount_types_kind_check CHECK ((kind = ANY (ARRAY['fixed'::text, 'percent'::text])));
alter table employee_payslips add constraint employee_payslips_payment_method_check CHECK ((payment_method = ANY (ARRAY['cash'::text, 'kpay'::text, 'wave'::text, 'bank'::text, 'other'::text])));
alter table employees add constraint employees_category_check CHECK ((category = ANY (ARRAY['esl_teacher'::text, 'admin_teacher'::text, 'admin_staff'::text, 'helper'::text, 'security'::text, 'cleaner'::text, 'driver'::text, 'accountant'::text, 'owner'::text, 'other'::text])));
alter table enrolments add constraint enrolments_status_check CHECK ((status = ANY (ARRAY['Active'::text, 'Break'::text, 'Left'::text])));
alter table inventory_movements add constraint inventory_movements_direction_check CHECK ((direction = ANY (ARRAY['IN'::text, 'OUT'::text, 'ADJUST'::text])));
alter table inventory_movements add constraint inventory_movements_reason_check CHECK ((reason = ANY (ARRAY['purchase'::text, 'sale'::text, 'give_to_student'::text, 'damage'::text, 'return'::text, 'opening_balance'::text, 'closing_count'::text, 'correction'::text])));
alter table invoice_lines add constraint invoice_lines_kind_check CHECK ((kind = ANY (ARRAY['class_fee'::text, 'book'::text, 'id'::text, 'tshirt'::text, 'guide'::text, 'fine'::text, 'discount'::text, 'other'::text])));
alter table invoices add constraint invoices_status_check CHECK ((status = ANY (ARRAY['open'::text, 'paid'::text, 'partial'::text, 'void'::text])));
alter table ledger_entries add constraint ledger_entries_source_check CHECK ((source = ANY (ARRAY['GeneralExpense'::text, 'OfficeExpense'::text, 'Auto'::text, 'Manual'::text])));
alter table payments add constraint payments_channel_check CHECK ((channel = ANY (ARRAY['cash'::text, 'kpay'::text, 'wave'::text, 'bank'::text, 'other'::text])));
alter table products add constraint products_kind_check CHECK ((kind = ANY (ARRAY['textbook'::text, 'tshirt'::text, 'id_card'::text, 'accessory'::text, 'other'::text])));
alter table schedule_assignments add constraint schedule_assignments_day_of_week_check CHECK ((day_of_week = ANY (ARRAY['Sat'::text, 'Sun'::text, 'Mon'::text, 'Tue'::text, 'Wed'::text, 'Thu'::text, 'Fri'::text])));
alter table section_teachers add constraint section_teachers_teaching_role_check CHECK ((teaching_role = ANY (ARRAY['MT'::text, 'CT'::text, 'SUB'::text, 'OBSERVER'::text, 'OTHER'::text])));
alter table students add constraint students_current_status_check CHECK ((current_status = ANY (ARRAY['Active'::text, 'Break'::text, 'Left'::text, 'Prospect'::text])));
alter table absences add constraint absences_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id);
alter table absences add constraint absences_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;
alter table attendance_marks add constraint attendance_marks_session_id_fkey FOREIGN KEY (session_id) REFERENCES class_sessions(id) ON DELETE CASCADE;
alter table attendance_marks add constraint attendance_marks_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table chart_of_accounts add constraint chart_of_accounts_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES chart_of_accounts(id);
alter table class_sessions add constraint class_sessions_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id);
alter table employee_payslips add constraint employee_payslips_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;
alter table employee_payslips add constraint employee_payslips_ledger_entry_id_fkey FOREIGN KEY (ledger_entry_id) REFERENCES ledger_entries(id);
alter table enrolments add constraint enrolments_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table enrolments add constraint enrolments_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id);
alter table event_budget_items add constraint event_budget_items_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;
alter table fee_schedule add constraint fee_schedule_level_id_fkey FOREIGN KEY (level_id) REFERENCES levels(id);
alter table inventory_movements add constraint inventory_movements_related_ledger_id_fkey FOREIGN KEY (related_ledger_id) REFERENCES ledger_entries(id) ON DELETE CASCADE;
alter table inventory_movements add constraint inventory_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
alter table inventory_movements add constraint inventory_movements_related_po_id_fkey FOREIGN KEY (related_po_id) REFERENCES purchase_orders(id);
alter table inventory_movements add constraint inventory_movements_related_invoice_id_fkey FOREIGN KEY (related_invoice_id) REFERENCES invoices(id);
alter table inventory_movements add constraint inventory_movements_related_student_id_fkey FOREIGN KEY (related_student_id) REFERENCES students(id);
alter table invoice_lines add constraint invoice_lines_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE;
alter table invoices add constraint invoices_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id);
alter table invoices add constraint invoices_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id);
alter table kpay_transactions add constraint kpay_transactions_matched_payment_fk FOREIGN KEY (matched_payment_id) REFERENCES payments(id);
alter table ledger_entries add constraint ledger_entries_account_id_fkey FOREIGN KEY (account_id) REFERENCES chart_of_accounts(id);
alter table ledger_entries add constraint ledger_entries_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
alter table payments add constraint payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id);
alter table payments add constraint payments_kpay_txn_id_fkey FOREIGN KEY (kpay_txn_id) REFERENCES kpay_transactions(id);
alter table payments add constraint payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id);
alter table po_items add constraint po_items_po_id_fkey FOREIGN KEY (po_id) REFERENCES purchase_orders(id) ON DELETE CASCADE;
alter table po_items add constraint po_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
alter table products add constraint products_level_id_fkey FOREIGN KEY (level_id) REFERENCES levels(id);
alter table purchase_orders add constraint purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
alter table schedule_assignments add constraint schedule_assignments_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id);
alter table schedule_assignments add constraint schedule_assignments_ct_employee_id_fkey FOREIGN KEY (ct_employee_id) REFERENCES employees(id);
alter table schedule_assignments add constraint schedule_assignments_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id);
alter table schedule_assignments add constraint schedule_assignments_mt_employee_id_fkey FOREIGN KEY (mt_employee_id) REFERENCES employees(id);
alter table section_teachers add constraint section_teachers_employee_id_fkey FOREIGN KEY (teacher_id) REFERENCES employees(id) ON DELETE RESTRICT;
alter table section_teachers add constraint section_teachers_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE;
alter table sections add constraint sections_level_id_fkey FOREIGN KEY (level_id) REFERENCES levels(id);
alter table sections add constraint sections_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id);
alter table student_discounts add constraint student_discounts_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table student_discounts add constraint student_discounts_discount_type_id_fkey FOREIGN KEY (discount_type_id) REFERENCES discount_types(id);
alter table students add constraint students_guardian_id_fkey FOREIGN KEY (guardian_id) REFERENCES guardians(id);
alter table teacher_payslips add constraint teacher_payslips_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(id);
alter table teacher_payslips add constraint teacher_payslips_employee_id_fkey FOREIGN KEY (teacher_id) REFERENCES employees(id) ON DELETE RESTRICT;
