CREATE INDEX absences_employee_month ON public.absences USING btree (employee_id, absent_date);
CREATE INDEX absences_section_id_idx ON public.absences USING btree (section_id);
CREATE INDEX attendance_marks_marked_by_idx ON public.attendance_marks USING btree (marked_by);
CREATE INDEX attendance_marks_student_id_idx ON public.attendance_marks USING btree (student_id);
CREATE INDEX audit_log_changed_by_idx ON public.audit_log USING btree (changed_by);
CREATE INDEX backups_created_at_idx ON public.backups USING btree (created_at DESC);
CREATE INDEX chart_of_accounts_parent_id_idx ON public.chart_of_accounts USING btree (parent_id);
CREATE INDEX class_sessions_session_date_idx ON public.class_sessions USING btree (session_date);
CREATE INDEX employee_payslips_ledger_entry_id_idx ON public.employee_payslips USING btree (ledger_entry_id);
CREATE INDEX employee_payslips_month ON public.employee_payslips USING btree (pay_month);
CREATE INDEX enrolments_active_section_idx ON public.enrolments USING btree (section_id) WHERE (end_date IS NULL);
CREATE INDEX enrolments_section_id_idx ON public.enrolments USING btree (section_id);
CREATE INDEX enrolments_student_id_idx ON public.enrolments USING btree (student_id);
CREATE INDEX event_budget_items_event_id_idx ON public.event_budget_items USING btree (event_id);
CREATE INDEX fee_schedule_level_id_effective_from_idx ON public.fee_schedule USING btree (level_id, effective_from);
CREATE INDEX inventory_movements_ledger_idx ON public.inventory_movements USING btree (related_ledger_id);
CREATE INDEX inventory_movements_product_id_movement_at_idx ON public.inventory_movements USING btree (product_id, movement_at);
CREATE INDEX inventory_movements_recorded_by_idx ON public.inventory_movements USING btree (recorded_by);
CREATE INDEX inventory_movements_related_invoice_id_idx ON public.inventory_movements USING btree (related_invoice_id);
CREATE INDEX inventory_movements_related_po_id_idx ON public.inventory_movements USING btree (related_po_id);
CREATE INDEX inventory_movements_related_student_id_idx ON public.inventory_movements USING btree (related_student_id);
CREATE INDEX invoice_lines_invoice_id_idx ON public.invoice_lines USING btree (invoice_id);
CREATE INDEX invoices_billing_month_idx ON public.invoices USING btree (billing_month);
CREATE INDEX invoices_created_by_idx ON public.invoices USING btree (created_by);
CREATE INDEX invoices_section_id_idx ON public.invoices USING btree (section_id);
CREATE INDEX invoices_status_month_idx ON public.invoices USING btree (status, billing_month) WHERE (status <> 'void'::text);
CREATE INDEX invoices_student_id_idx ON public.invoices USING btree (student_id);
CREATE UNIQUE INDEX invoices_student_month_uidx ON public.invoices USING btree (student_id, billing_month) WHERE (status <> 'void'::text);
CREATE INDEX kpay_transactions_matched_idx ON public.kpay_transactions USING btree (matched) WHERE (matched = false);
CREATE INDEX kpay_transactions_matched_payment_idx ON public.kpay_transactions USING btree (matched_payment_id);
CREATE INDEX kpay_transactions_txn_at_idx ON public.kpay_transactions USING btree (txn_at);
CREATE INDEX ledger_entries_account_id_idx ON public.ledger_entries USING btree (account_id);
CREATE INDEX ledger_entries_created_by_idx ON public.ledger_entries USING btree (created_by);
CREATE INDEX ledger_entries_entry_date_idx ON public.ledger_entries USING btree (entry_date);
CREATE INDEX ledger_entries_product_idx ON public.ledger_entries USING btree (product_id);
CREATE INDEX payments_invoice_id_idx ON public.payments USING btree (invoice_id);
CREATE INDEX payments_kpay_txn_id_idx ON public.payments USING btree (kpay_txn_id);
CREATE INDEX payments_paid_at_idx ON public.payments USING btree (paid_at);
CREATE INDEX payments_recorded_by_idx ON public.payments USING btree (recorded_by);
CREATE INDEX payments_student_id_idx ON public.payments USING btree (student_id);
CREATE INDEX po_items_po_id_idx ON public.po_items USING btree (po_id);
CREATE INDEX po_items_product_id_idx ON public.po_items USING btree (product_id);
CREATE INDEX products_level_id_idx ON public.products USING btree (level_id);
CREATE INDEX purchase_orders_supplier_id_idx ON public.purchase_orders USING btree (supplier_id);
CREATE INDEX schedule_assignments_section_id_idx ON public.schedule_assignments USING btree (section_id);
CREATE INDEX schedule_ct_idx ON public.schedule_assignments USING btree (ct_employee_id, month);
CREATE INDEX schedule_month_idx ON public.schedule_assignments USING btree (month);
CREATE INDEX schedule_mt_idx ON public.schedule_assignments USING btree (mt_employee_id, month);
CREATE INDEX schedule_room_idx ON public.schedule_assignments USING btree (room_id, month);
CREATE INDEX section_teachers_teacher_id_idx ON public.section_teachers USING btree (teacher_id);
CREATE INDEX sections_room_id_idx ON public.sections USING btree (room_id);
CREATE INDEX student_discounts_discount_type_id_idx ON public.student_discounts USING btree (discount_type_id);
CREATE INDEX student_discounts_student_id_idx ON public.student_discounts USING btree (student_id);
CREATE INDEX students_current_status_idx ON public.students USING btree (current_status);
CREATE INDEX students_english_name_idx ON public.students USING btree (english_name);
CREATE INDEX students_guardian_id_idx ON public.students USING btree (guardian_id);
CREATE INDEX students_status_name_idx ON public.students USING btree (current_status, english_name);
CREATE INDEX teacher_payslips_pay_month_idx ON public.teacher_payslips USING btree (pay_month);
CREATE INDEX teacher_payslips_payment_id_idx ON public.teacher_payslips USING btree (payment_id);
